name: Execute Jupyter Notebook

on:
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nbconvert nbformat ipykernel
          python -m ipykernel install --user --name python3 --display-name "Python 3"

      - name: List Jupyter Kernels
        run: jupyter kernelspec list  # This will help verify if the kernel was installed correctly

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute LinearRegression.ipynb
